skip-check:

  #================================================================================================
  # Other
  #================================================================================================
  # [CKV_TF_1] Ensure Terraform module sources use a commit hash
  - CKV_TF_1 # Not required for demo.

  #================================================================================================
  # Key Vaults
  #================================================================================================
  # [CKV_AZURE_41] Ensure that the expiration date is set on all secrets
  - CKV_AZURE_41 # Not required for demo.
  # [CKV_AZURE_42] Ensure the key vault is recoverable
  - CKV_AZURE_42 # Not required for demo.
  # [CKV_AZURE_109] Ensure that key vault allows firewall rules settings
  - CKV_AZURE_109 # FALSE POSITIVE - the firewall is enabled and rules are set.
  # [CKV_AZURE_110] Ensure that key vault enables purge protection
  - CKV_AZURE_110 # Not required for demo.
  # [CKV_AZURE_112] Ensure that key vault key is backed by HSM
  - CKV_AZURE_112 # Not required for demo.
  # [CKV_AZURE_114] Ensure that key vault secrets have "content_type" set
  - CKV_AZURE_114 # Not required for demo.
  # [CKV2_AZURE_32] Ensure private endpoint is configured to key vault
  - CKV2_AZURE_32 # Private endpoint will be enabled once mdp is available.

  #================================================================================================
  # ACR
  #================================================================================================
  # [CKV_AZURE_139] Ensure ACR set to disable public networking
  - CKV_AZURE_139 # Not required for demo; requires a standard or premium sku.
  # [CKV_AZURE_163] Enable vulnerability scanning for container images.
  - CKV_AZURE_163 # Not required for demo; requires a standard or premium sku.
  # [CKV_AZURE_164] Ensures that ACR uses signed/trusted images
  - CKV_AZURE_164 # Not required for demo; apps use custom local built images only.
  # [CKV_AZURE_165] Ensure geo-replicated container registries to match multi-region container deployments
  - CKV_AZURE_165 # Not required for demo; requires a standard or premium sku.
  # [CKV_AZURE_166] Ensure container image quarantine, scan, and mark images verified
  - CKV_AZURE_166 # Not required for demo; requires a standard or premium sku.
  # [CKV_AZURE_233] Ensure Azure Container Registry (ACR) is zone redundant
  - CKV_AZURE_233 # Not required for demo; requires a standard or premium sku.
  # [CKV_AZURE_237] Ensure dedicated data endpoints are enabled.
  - CKV_AZURE_237 # Not required for demo; requires a standard or premium sku.

  #================================================================================================
  # AKS
  #================================================================================================
  # [CKV_AZURE_4] Ensure AKS logging to Azure Monitoring is Configured
  - CKV_AZURE_4 # FALSE POSITIVE - AKS logging to Azure Monitoring is Configured.
  # [CKV_AZURE_115] Ensure that AKS enables private clusters
  - CKV_AZURE_115 # API firewall is used instead.
  # [CKV_AZURE_117] Ensure that AKS uses disk encryption set
  - CKV_AZURE_117 # Not required for demo.
  # [CKV_AZURE_141] Ensure AKS local admin account is disabled
  - CKV_AZURE_141 # FALSE POSITIVE - local admin account is disabled.
  # [CKV_AZURE_168] Ensure Azure Kubernetes Cluster (AKS) nodes should use a minimum number of 50 pods.
  - CKV_AZURE_168 # FALSE POSITIVE - nodes support upto 100 pods.
  # [CKV_AZURE_170] Ensure that AKS use the Paid Sku for its SLA
  - CKV_AZURE_170 # Not required for demo; requires a standard or premium sku.
  # [CKV_AZURE_172] Ensure autorotation of Secrets Store CSI Driver secrets for AKS clusters
  - CKV_AZURE_172 # FALSE POSITIVE - secret rotation enabled.
  # [CKV_AZURE_226] Ensure ephemeral disks are used for OS disks
  - CKV_AZURE_226 # Ephemeral disks arent supported on selected vm_size.
  # [CKV_AZURE_227] Ensure that the AKS cluster encrypt temp disks, caches, and data flows between Compute and Storage resources
  - CKV_AZURE_227 # Not required for demo.
  # [CKV_AZURE_232] Ensure that only critical system pods run on system nodes
  - CKV_AZURE_232 # FALSE POSITIVE - only critical system pods run on system nodes.
  # [CKV2_AZURE_29] Ensure AKS cluster has Azure CNI networking enabled
  - CKV2_AZURE_29 # FALSE POSITIVE - AKS cluster has Azure CNI networking enabled.
